import { test, expect } from '@playwright/test';

test('Login Test Generated By PlaWright with CodeGen', async ({ page }) => {

  await page.goto('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');

  await page.getByPlaceholder('Username').fill('Admin');
  
  await page.getByPlaceholder('Password').fill('admin123');
  
  await page.getByRole('button', { name: 'Login' }).click();
  await expect(page).toHaveURL('https://opensource-demo.orangehrmlive.com/web/index.php/dashboard/index');

  await page.waitForTimeout(2000);

  await page.getByRole('banner').getByRole('img', { name: 'profile picture' }).click();
  
  await page.getByRole('menuitem', { name: 'Logout' }).click();
  await expect(page).toHaveURL('https://opensource-demo.orangehrmlive.com/web/index.php/auth/login');
});